image: eve-debug
org: lfedge
network: yes
config:
  binds:
    - /dev:/dev
    - /etc/resolv.conf:/etc/resolv.conf
    - /run:/run
    - /var/log:/var/log/dom0
    - /:/hostfs
    - /var/persist:/persist
    - /var/config:/config
  net: host
  capabilities:
    - all
  pid: host
